apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stressor-deployment
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cpu-stressor
  template:
    metadata:
      labels:
        app: cpu-stressor
    spec:
      containers:
      - name: cpu-stressor
        image: ghcr.io/victorcodesseira/k8s_pod_cpu_stressor:main
        args:
          - "-cpu=0.2"
          - "-duration=10s"
          - "-forever"
        resources:
          limits:
            cpu: "400m"
          requests:
            cpu: "200m"